Actualizar build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,7 +8,6 @@ on:
         required: true
 
 jobs:
-
   build:
     runs-on: ubuntu-latest
     
@@ -25,11 +24,22 @@ jobs:
     - name: Grant execute permission for gradlew
       run: chmod +x ./gradlew
         
-    - name: Configure and build
-      run: |
-        ./gradlew assembleRelease
+    - name: Build with Gradle
+      run: ./gradlew assembleRelease --stacktrace
         
-    - uses: actions/upload-artifact@v4
+    - name: Verify APK exists
+      run: |
+        if [ -f app/build/outputs/apk/release/app-release.apk ]; then
+          echo "APK file exists"
+        else
+          echo "APK file not found"
+          exit 1
+        fi
+        
+    - name: Upload APK
+      uses: actions/upload-artifact@v4
       with:
         name: ModMenu-${{ github.event.inputs.package_name }}
         path: app/build/outputs/apk/release/app-release.apk
+        if-no-files-found: error
+        retention-days: 90
